### ISSUE TITLE
Is there a "Dark Minima" theme out there? 

### ISSUE THREAD

**Issue by yamlCase** [jekyll/minima#143]
I really like the features and layout of the minima theme, but wish it could be inverted on the colors.  Is there a minima based theme out there that is dark?

**Comment by jasonrhaas** [comment]
Could probably tinker around with the CSS a bit and get some decent results.  Probably the easiest way is to fork the repo and edit the minima .scss files directly.

**Comment by edm00se** [comment]
Here's a quick and dirty example of how to achieve it. It likely doesn't account for everything, but is a starting reference point.

```scss
---
---
/*
 * assets/main.scss
 * the dashed lines above are required
 */

$background-color: #1d1d1d; /* a dark, off-black for the bg */
$text-color: #e6e6e6; /* an off-white for the text */
$grey-color-light: #565656; /* for the border-top separators */
$grey-color-dark: #adadad; /* such as the site title in the header, visited */

@import "{{ site.theme }}";
```

Here's an example image of how that will turn out on the home page.

![image](https://user-images.githubusercontent.com/622118/32670642-08356080-c60a-11e7-8d14-e91a8428b57b.png)
