### ISSUE TITLE
Page masthead image above/next to/instead of site title?

### ISSUE THREAD

**Issue by uliwitness** [jekyll/minima#264]
Minima is a gorgeously simple theme, but given most sites have some sort of logo or masthead image, I would think allowing for an (optional) masthead image to go with the site title would be an addition that doesn't yet constitute feature-creep. I'm thinking of something where you specify a `masthead-image`, `masthead-left-image` or `masthead-above-image` in the `_config.yml`.

Would anyone be interested in adding this? If I managed to somehow add this feature to my copy of Minima, would there be interest in merging that back into the mainline?

**Comment by uliwitness** [comment]
Okay, I managed to build this. In `_includes/header.html`, replace the existing title output code with:

```yaml
	{%- if site.masthead -%}
	<a href="{{ "/" | relative_url }}"><img class="site-masthead" src="{{ site.masthead | relative_url }}" alt="{{ site.title | escape }}" /></a>
	{%- else -%}
	<a class="site-title" rel="author" href="{{ "/" | relative_url }}">{{ site.title | escape }}</a>
	{%- endif -%}
```

In `_sass/minima/_layout.scss`, add the following CSS class:

```css
.site-masthead {
  display: block;
  margin-left: auto;
  margin-right: auto;
  padding-top: $spacing-unit / 2;
  padding-bottom: $spacing-unit / 2;
}
```

And in `_config.yml` add:

```yml
# Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
# masthead: /my_masthead.jpg
```

Would be grateful if someone could put that into the official Gem.
