### ISSUE TITLE
_config.yaml and frontmatter not being honored in version 2.5.0

### ISSUE THREAD

**Issue by drewboardman** [jekyll/minima#350]
I'm using 2.5.0 ([source that I'm referring to](https://github.com/drewboardman/drewboardman.github.io/blob/master/_config.yml#L26)).

Disclaimer: I'm restarted the server and re-building between steps. I've seen that as a common gotcha here.

**Problem**: Changing some options in `_config.yml`, and frontmatter on posts is not being reflected in the browser.

**Example**: Making a change to the theme in `_config.yml` and changing a post to use `classes: wide`.

```yaml

#_config.yml

# Build settings
markdown: kramdown
theme: minima
minimal_mistakes_skin: "air"  # <--- changed this value
plugins:
  - jekyll-feed


#_posts/some_post.markdown
---
layout: post
title:  "Typeclasses in Scala"
classes: wide                          #<----changed this value
date:   2019-03-18 19:52:02 -0500
categories: jekyll update
---
...
```

Stopping the server and re-running build with debug flags

```
$ LISTEN_GEM_DEBUGGING=1 be jekyll build
Configuration file: /home/drew/code/drewboardman.github.io/_config.yml
            Source: /home/drew/code/drewboardman.github.io
       Destination: /home/drew/code/drewboardman.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.174 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Re-run the server

```
$ be jekyll serve
Configuration file: /home/drew/code/drewboardman.github.io/_config.yml
            Source: /home/drew/code/drewboardman.github.io
       Destination: /home/drew/code/drewboardman.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.171 seconds.
 Auto-regeneration: enabled for '/home/drew/code/drewboardman.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

I'm hitting `localhost:4000` in an incognito tab. Reloading and there are no changes.

If I change content in a blogpost it shows up instantly in the browser. No issues there.
