### ISSUE TITLE
optionally allow to force the drop down navigation

### ISSUE THREAD

**Issue by aoloe** [jekyll/minima#367]
Nowadays, more and more sites only use the drop down navigation.

In my case I have a few menu entries, but they are not very important and they are cluttering the header...

**Comment by aoloe** [comment]
I have a temporary solution my adding to my _local_ `assets/main.scss` the following formatting:

```scss
---
---

@import "{{ site.theme }}";

.site-nav {
    position: absolute;
    top: 9px;
    right: $spacing-unit / 2;
    background-color: $background-color;
    border: 1px solid $grey-color-light;
    border-radius: 5px;
    text-align: right;

    label[for="nav-trigger"] {
      display: block;
      float: right;
      width: 36px;
      height: 36px;
      z-index: 2;
      cursor: pointer;
    }

    .menu-icon {
      display: block;
      float: right;
      width: 36px;
      height: 26px;
      line-height: 0;
      padding-top: 10px;
      text-align: center;

      > svg {
        fill: $grey-color-dark;
      }
    }

    input ~ .trigger {
      clear: both;
      display: none;
    }

    input:checked ~ .trigger {
      display: block;
      padding-bottom: 5px;
    }

    .page-link {
      display: block;
      padding: 5px 10px;

      &:not(:last-child) {
        margin-right: 0;
      }
      margin-left: 20px;
    }
}
```

If I can find a solution that uses a variable set from my .scss file, I'll make a pull request...
