### ISSUE TITLE
Why don't specify the styles of h5 and h6?

### ISSUE THREAD

**Issue by alexhuangster** [jekyll/minima#374]
In `_layout.scss`, the styles of `h2` to `h4` are specified.

```scss
.post-content {
  margin-bottom: $spacing-unit;

  h2 {
    @include relative-font-size(1.75);

    @media screen and (min-width: $on-large) {
      @include relative-font-size(2);
    }
  }

  h3 {
    @include relative-font-size(1.375);

    @media screen and (min-width: $on-large) {
      @include relative-font-size(1.625);
    }
  }

  h4 {
    @include relative-font-size(1.125);

    @media screen and (min-width: $on-large) {
      @include relative-font-size(1.25);
    }
  }
}
```

But why don't specify the styles of h5 and h6?
