### ISSUE TITLE
[ question ] what is the right way to add.mastodon username in config.yml

### ISSUE THREAD

**Issue by leela52452** [jekyll/minima#406]
i have seen to add mastodon username in .config.yml.

however, @ symbol is not allowed according to [yaml spec](https://yaml.org/spec/1.2/spec.html) ( thats what i interpreted after reading ), i may be wrong.

can you also please instructions for both **github** & **gitlab** pages.

thank you very much.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least two months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is core to this project and why you feel more than 80% of users would find this beneficial.

This issue will automatically be closed in two months if no further activity occurs. Thank you for all your contributions.

**Comment by ashmaroli** [comment]
The current release is v2.5.1
Specify mastodon instances as a top-level array in your config file:
```yaml
github_username:  johndoe

# Mastodon instances
mastodon:
- username: johndoe
  instance: example.com
- username: janedoe
  instance: another-example.com
```
