### ISSUE TITLE
cannot remove email, github icon, rss icon from footer [master branch]

### ISSUE THREAD

**Issue by KushGoyal** [jekyll/minima#444]
When using the code from branch I am not able to remove email and social icons from the footer.

The default config file has email, GitHub, rss defined which are not removed.

**Comment by ashmaroli** [comment]
Just comment them out in the config file.
(*Don't forget to restart your local webserver after every change to the config file*)

**Comment by KushGoyal** [comment]
@ashmaroli Not working even after commenting out. I tried putting blank values too. Use the below config to reproduce this. Use the code in the master branch.

```yaml
title: My blog
author: Me
description: >- # this means to ignore newlines until "baseurl:"
  my blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyll
linkedin_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
show_excerpts: true
permalink: /:title/
header_pages:
  - about.markdown
minima:
  social_links:
    twitter: jekyll
    linkedin: jekyll
```
