### ISSUE TITLE
Overwriting theme not working

### ISSUE THREAD

**Issue by Atcold** [jekyll/minima#541]
I'm using Minima 3.0, dark theme.

```yml
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
```

On Chrome I see a horizontal light grey bar on top (right below the URL bar).

![image](https://user-images.githubusercontent.com/2119355/93012454-86808a00-f56e-11ea-88f5-30f3d9a72ed2.png)

To remove such bar, I am using Sass overwriting.
My `_sass/minima/custom-styles.scss` looks like this:

```scss
/**
 * Site header
 */
.site-header {
  // border-top: 5px solid $border-color-03;
  border-bottom: 1px solid $border-color-01;
  min-height: $spacing-unit * 1.865;
  line-height: $base-line-height * $base-font-size * 2.25;

  // Positioning context for the mobile navigation icon
  position: relative;
}
```

But the new header is not been picked up.
Am I doing anything wrong?

I thought #474 was solved by #478, but I may have misunderstood the documentation.

**Comment by ashmaroli** [comment]
Simply commenting out `border-top: 5px solid $border-color-03;` won't work.
You'll have to override explicitly:
```css
.site-header {
  border-top: none;
  border-bottom: 1px solid $border-color-01;
  ...
}
```
