### ISSUE TITLE
Google Analytics data not received

### ISSUE THREAD

**Issue by CLeBeRFR** [jekyll/minima#561]
I create an account on Google Analytics. It generates me an ID which starts with `G-BXXXXXX`.
I put it in `_config.yml`:
```yml
title: My Blog
email:
google_analytics: G-BXXXXXX
description: >- # this means to ignore newlines until "baseurl:"
  My blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
```
When I visit the page, I see the code :
```javascript
<script>
if(!(window.doNotTrack === "1" || navigator.doNotTrack === "1" || navigator.doNotTrack === "yes" || navigator.msDoNotTrack === "1")) {
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'G-BXXXXXX', 'auto');
  ga('send', 'pageview');
}
</script>
```
My problem is maybe linked with #555
