### ISSUE TITLE
undefined variable minima

### ISSUE THREAD

**Issue by vivi90** [jekyll/minima#597]
Even if i create a completely fresh Jekyll project and update the minimal gems to latest version `2.5.1`, i run into the following issue:
```bash
$ jekyll build --trace
Configuration file: F:/Projekte/JekyllTest/_config.yml
            Source: F:/Projekte/JekyllTest
       Destination: F:/Projekte/JekyllTest/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid error (line 7): undefined variable minima in C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/minima-2.5.1/_layouts/post.html
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:62:in `block in evaluate': Liquid error (line 7): undefined variable minima (Liquid::UndefinedVariable)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `each_index'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `evaluate'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/context.rb:159:in `evaluate'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:131:in `render_liquid'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:194:in `render_layout'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:163:in `place_in_layouts'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:93:in `render_document'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `block in render_docs'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `each_value'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `render_docs'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby30-x64/bin/jekyll:23:in `load'
        from C:/Ruby30-x64/bin/jekyll:23:in `<main>'
```
I am using these `_config.yml` for demonstration, because i require strict settings for our development:
```yaml
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Liquid settings
liquid:
  error_mode        : strict # Response to errors (Possible values: 'lax', 'warn' or 'strict').
  strict_filters    : true # Catch non-existing filters.
  strict_variables  : true # Catch non-assigned variables.
```
Here is my example commit: 
https://github.com/vivi90/reproduce-jekyll-issues/commit/1756c0492ee85f34f0ca5bffb511cc12a56bf424

If i use the setting `strict_variables: false`, then i will not be able to see my own issues as well.

An fix would be great, thank you very much!

**Comment by ashmaroli** [comment]
Hello @vivi90
The error could be from [this line](https://github.com/jekyll/minima/blob/38a84a949f9753c4542e25f422935f59b4913053/_layouts/post.html#L10)

While we may or may not patch this for v.2.x, you can try and resolve the issue at your end by having the following in your config file:

```yaml
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
```
