### ISSUE TITLE
Can't change theme to dark

### ISSUE THREAD

**Issue by EmilySeville7cfg** [jekyll/minima#624]
I have the following [_config.yml](https://replit.com/@EmilySeville7cfg/console-utilsgithubio#docs/_config.yml)  file:

```yml
title: Console Utils
email: EmilySeville7cf@example.com
description: Console utils written in different languages by Emily Seville.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EmilySeville7cf
github_username:  EmilySeville7cfg

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
  - test.markdown

minima:
  skin: dark
```

But `skin: dark` doesn't work as expected. Please describe why it happens or what I am missing.
