### ISSUE TITLE
Social Media Links Disappear

### ISSUE THREAD

**Issue by elyshaffir** [jekyll/minima#628]
Recently in my [blog](https://github.com/elyshaffir/Taiga-Blog) I switched to using this version of minima instead of the gem's version and for some reason the footer's social media links have disappeared. I've seen another [similar unsolved case](https://issueexplorer.com/issue/jekyll/minima/599) but that's about it. Do you have any idea on why this might be happening?

**Comment by ashmaroli** [comment]
The repository version isn't backwards-compatible with the gem-version.
Social media links are now nested under key `minima.social_links`:
```yaml
minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
```
