### ISSUE TITLE
site.author.name displays on top of page?

### ISSUE THREAD

**Issue by rahil627** [jekyll/minima#632]
i understand it appears in the footer (includes), but i don’t see it in the head ‘n header files... i feel like it’s a debug output? no clue.

![E61B4B0C-A600-40AB-A858-822F90BFC706](https://user-images.githubusercontent.com/1132053/148558486-06fe42d2-c675-4190-883c-fc50f81fc826.png)

```
# config.yml
author:
  name: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>
  email: '' # error without it?
```

_note: the picture has an edited footer, without the ‘| escape’, so that my links now work. But the problem occurs with or without that._
