### ISSUE TITLE
Where are all the files?

### ISSUE THREAD

**Issue by michaelgwelch** [jekyll/minima#708]
Am I supposed to have the layout structure as written up in the README?

I started my site by using the getting started guide at GitHub https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

Looks like `minima` is the default. 

I read the README and see the list of dirs and files. But I don't have most of those in my setup.

Here's what I see:

```bash
✗ ls -l 
total 56
-rw-r--r--  1 mgwelch  staff   419 Jan 31 21:03 404.html
-rw-r--r--  1 mgwelch  staff  1391 Jan 31 21:13 Gemfile
-rw-r--r--  1 mgwelch  staff  7479 Jan 31 21:13 Gemfile.lock
-rw-r--r--  1 mgwelch  staff  2364 Jan 31 21:27 _config.yml
drwxr-xr-x@ 3 mgwelch  staff    96 Jan 31 21:04 _posts
drwxr-xr-x@ 8 mgwelch  staff   256 Jan 31 21:23 _site
-rw-r--r--  1 mgwelch  staff   539 Jan 31 21:03 about.markdown
-rw-r--r--  1 mgwelch  staff   175 Jan 31 21:03 index.markdown
```

So for example, I wanted to play around with the social media links. I added

```yaml
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/my_kl" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
    - { platform: mastodon, user_url: "https://mast.mmwelch.net/@michael" }
```

to the `_config.yml` file and served up the site. But the page doesn't reflect any changes to the social links I made. I think this is because I don't have any of the `_includes`.

Should I start over with different instructions than the GitHub Pages instructions?

Am I missing the obvious documentation for using this theme?

Thanks

This is macOS 13.2, ruby 3.1.3, and minima 2.5.1 (I think based on the Gemfile.lock) (and I'm not sure what else is relevant).
