### ISSUE TITLE
Setting dark theme in `_config.yml` appears to be ignored

### ISSUE THREAD

**Issue by joshbuker** [jekyll/minima#717]
Using `minima`, setting the theme to dark inside of `_config.yml` appears to be getting ignored:

```yml
minima:
  skin: dark
```

The other configuration appears to be getting pulled in correctly, so it's not an issue of `_config.yml` being ignored entirely. It's specifically the theme value that has no effect.

To replicate, see: https://github.com/joshbuker/gsd-tools/tree/2269b5ba3a054844eaaf19598a6870a6245f658b/website

The issue happens both when running locally and when deployed via Cloudflare pages.

**Comment by corite** [comment]
I have the same Issue, both with a local and a Github Pages deployment.

**Comment by joshbuker** [comment]
For folks looking to use dark theme before 3.0 gets released, update your files as follows:

`_config.yml`
```yml
# Disable using the latest Minima release
#theme: minima
# And instead pull straight from GitHub via jekyll remote theme
remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-feed

minima:
  skin: dark
```

`Gemfile`
```ruby
group :jekyll_plugins do
  gem 'jekyll-seo-tag'
  gem 'jekyll-feed'
  gem 'jekyll-remote-theme'
end
```
