### ISSUE TITLE
Trying to switch default theme is not working.

### ISSUE THREAD

**Issue by iankingcoop** [jekyll/minima#754]
Trying to switch default theme. Not working. I started with a basic github pages site. The only thing that works is the classic theme.

```
minima:
  skin: dark
```

**Comment by ashmaroli** [comment]
Are you using the gem version of the theme or the remote version? You need the remote version to use skins.
To pull in the remote version, use the following config entries:

```yaml
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
```
