### ISSUE TITLE
Author Configuration Parsing Problem in `_config.yml`

### ISSUE THREAD

**Issue by vinitshahdeo** [jekyll/minima#779]
**Description:**

In the [`_config.yml`](https://github.com/vinitshahdeo/50DaysOfJavaScript/blob/develop/_config.yml) file of the [#50DaysOfJavaScript](https://github.com/vinitshahdeo/50DaysOfJavaScript) repository, I've provided **author** configuration settings in YAML format. However, instead of appearing as expected, it seems that the configuration is being interpreted as a JSON object. This issue is causing unexpected behavior in the display of the footer of the hosted GitHub page.

**Provided Configuration:**
```yaml
title: 50DaysOfJavaScript — Solve one question daily to ace your next interview!
author:
  name: Vinit Shahdeo
  email: vinitshahdeo[at]gmail[dot]com
```

**Observed Configuration:**
```json
{"name"=>"Vinit Shahdeo", "email"=>"vinitshahdeo@gmail.com"}
```

**Attached Screenshot:**

[![Screenshot 2024-02-18 at 5 38 56 AM](https://github.com/jekyll/minima/assets/20594326/ce4d3945-4524-4088-b737-d636f349f359)](https://vinitshahdeo.github.io/50DaysOfJavaScript/)

**Additional Details:**
- **Repository:** [50DaysOfJavaScript Repository](https://github.com/vinitshahdeo/50DaysOfJavaScript)
- **GitHub Page:** [50DaysOfJavaScript GitHub Page](https://vinitshahdeo.github.io/50DaysOfJavaScript/)

Kindly advise on any necessary actions or configurations to rectify this issue. Your help is much appreciated. Please let me know if you need further information or clarification. 

Thank you for your attention to this matter.
