### ISSUE TITLE
Socials Not Appearing in Footer

### ISSUE THREAD

**Issue by alexcw-5** [jekyll/minima#807]
Hello,

I recently tried changing my site's theme to be minima with the "auto" skin. This had the side effect of really messing with my footer. I have it pretty much back to the way I want except I can't get my github or linkedin to appear in the footer. I took the following code and modified it to be the correct links but so far it is not appearing
`minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }'
   `
(Also if there was a better way to enable dark mode than this please let me know, I feel that I may have slightly overcomplicated this somehow.

Thank you for your time,
Alex

**Comment by ashmaroli** [comment]
Hello @alexcw-5,
I took a look at your repository and found an issue with your config file: You seem to have defined the `minima` setting twice with differing values:

```yaml
# _config.yml

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/alexcw-5" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/acacereswright" }

# Build settings
#theme: minima
remote_theme: jekyll/minima
minima:  
  skin: auto
```
You may *inspect* which definition got preference by having the following somewhere in your layouts / markup:
```
<pre>
{{ site.minima | jsonify }}
</pre>
```

To fix, combine the two definitions:

```yaml
# _config.yml

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/alexcw-5" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/acacereswright" }
```
