### ISSUE TITLE
Social platform icons now restricted to Font Awesome library fa-brands

### ISSUE THREAD

**Issue by pfirpfel** [jekyll/minima#843]
Regarding #839:

I understand that in most cases, this feature is now much simpler to use. But you are limited on what **brand** icons fontawesome has.

Would it be possible to still support the old icon system as a fallback?
Or not limit the icons to the fa-brands namespace in fontawesome? In my case being able to switch to `fa-regular` instead of `fa-brands` would be enough.

**Comment by ashmaroli** [comment]
We don't intend to support the old icon system alongside the current Font Awesome based system due to reasons mentioned in #839. Limiting support to just `fa-brands` was a conscious decision.

However, I am curious as to which `fa-regular` icons you intend to render as part of the *social-icons* list. If its the `envelop` icon to denote `email`, then I believe that is duplicating the info rendered elsewhere in the footer itself. You are free to customize the `_includes/footer.html` to change the rendering of footer or just `_includes/social.html` at your end if you want to render the `envelop` icon as part of *social-links*.

**Comment by pfirpfel** [comment]
I used to have more or less `fa-calendar` as an icon. But then it would need `fa-brands` changed into `fa-regular`. Same for `fa-envelope`.

I guess right now, the only way is to override the includes as you said. Being able to override the fontawesome "namespace" (`fa-brands` being the default) per social item would be cool though.

**Comment by pfirpfel** [comment]
This is how I solved it in my `social.html` for now:

```html
<span class="grey fa-{{ entry.fa_namespace | default: "brands" }} fa-{{ entry.icon }} fa-lg"></span>
```

Config:
```yaml
minima:
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
    - title: Email Jekyll
      icon: envelope
      fa_namespace: regular
      url: "mailto:jekyll@example.com"
````
