### ISSUE TITLE
Broken navigation

### ISSUE THREAD

**Issue by jpomykala** [jekyll/minima#864]
This line broke existing navigation:
https://github.com/jekyll/minima/commit/9258979206c8e90e4c0c15de4b370e071a2b4f2b#diff-c0311c1df17d5d714db46ca1401ad374a35de861a461d211c6c947f1b2194034R5

The commit assumes that my header pages will be under a different key in `_config.yml` while the original version uses:

```
# _config.yml
header_pages:
  - photos.md
  - posts.md
  - projects.md
  - other.md
```

and the new one assumes:
```
# _config.yml
site:
   minima:
      nav_page:
  - photos.md
  - posts.md
  - projects.md
  - other.md
```

Is there any changelog regarding Minima v3?

If you also dealing with the issue you can fix it using older version:
```
# Gemfile
gem "minima", github: "jekyll/minima", ref: "1e8a445e8fd7280d0fd9d448c0f71c93a2565837"
```
and everything will back to normal.

**Comment by ashmaroli** [comment]
FYI, the following in your comment is syntactically-incorrect / invalid YAML:
```yaml
# _config.yml
site:
   minima:
      nav_page:
  - photos.md
  - posts.md
  - projects.md
  - other.md
```
YAML is *indentation-sensitive*.

---
P.S. I won't be reverting `site.minima.nav_pages` back to `site.header_pages`.
