### ISSUE TITLE
How to combine external URLs and local pages in nav_pages header navigation menu

### ISSUE THREAD

**Issue by larshelge** [jekyll/minima#896]
Thanks for a great theme and good work!

Question about the header navigation menu. I would like to combine regular links to local pages, with URL links to external web sites.

Example to illustrate for `_config.yml`, where "solutions.html" is a regular local page.

```yaml
minima
  nav_pages:
    - solutions.html
    - learn.html
```

Instead I want "Learn" to point to another site, say "https://www.learn.org", something like this:

```yaml
minima
  nav_pages:
    - title: Solutions
      url: /solutions/
    - title: Learn
      url: https://www.learn.org
```

Is this currently supported in a way?
